// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC_uAgtGGhmARUAViuUG-P6PeyOgPhpenk',
    appId: '1:32276712840:web:84a38b9a208a319c12fe3d',
    messagingSenderId: '32276712840',
    projectId: 'shere-4c8bc',
    authDomain: 'shere-4c8bc.firebaseapp.com',
    databaseURL: 'https://shere-4c8bc-default-rtdb.firebaseio.com',
    storageBucket: 'shere-4c8bc.firebasestorage.app',
    measurementId: 'G-CXYTGBQVTB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCPneNi7xi_JuzrMk0k48eK153HyQo_MmE',
    appId: '1:32276712840:android:ee8770688384b62312fe3d',
    messagingSenderId: '32276712840',
    projectId: 'shere-4c8bc',
    databaseURL: 'https://shere-4c8bc-default-rtdb.firebaseio.com',
    storageBucket: 'shere-4c8bc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC1WlV1EVR_wqS6HKClNxSCm0kTnZAzj1Q',
    appId: '1:32276712840:ios:756a42859f652e6512fe3d',
    messagingSenderId: '32276712840',
    projectId: 'shere-4c8bc',
    databaseURL: 'https://shere-4c8bc-default-rtdb.firebaseio.com',
    storageBucket: 'shere-4c8bc.firebasestorage.app',
    iosBundleId: 'com.example.sphereApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC1WlV1EVR_wqS6HKClNxSCm0kTnZAzj1Q',
    appId: '1:32276712840:ios:756a42859f652e6512fe3d',
    messagingSenderId: '32276712840',
    projectId: 'shere-4c8bc',
    databaseURL: 'https://shere-4c8bc-default-rtdb.firebaseio.com',
    storageBucket: 'shere-4c8bc.firebasestorage.app',
    iosBundleId: 'com.example.sphereApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC_uAgtGGhmARUAViuUG-P6PeyOgPhpenk',
    appId: '1:32276712840:web:52a19009dd73c1b112fe3d',
    messagingSenderId: '32276712840',
    projectId: 'shere-4c8bc',
    authDomain: 'shere-4c8bc.firebaseapp.com',
    databaseURL: 'https://shere-4c8bc-default-rtdb.firebaseio.com',
    storageBucket: 'shere-4c8bc.firebasestorage.app',
    measurementId: 'G-00DLL2M41Z',
  );
}
